### PR TITLE
Change wording & add code highlighting

### PR DESCRIPTION
**Pull request by rugk**
SHA256 hashes are not signatures, but hashes…

For real signatures I'd recommend signing your git tags.

### CODE REVIEW

**Comment by dbrgn** [comment]
Same as https://github.com/saltyrtc/saltyrtc-task-webrtc-java/pull/9#issuecomment-262635707.

Our tags are actually signed (signing key is E7ADD9914E260E8B35DFB50665FDE935573ACDA6).

**Comment by dbrgn** [comment]
By the way, why are your commits 11 minutes in the future? It even breaks the git commit form...

**Comment by rugk** [comment]
> Our tags are actually signed (signing key is E7ADD9914E260E8B35DFB50665FDE935573ACDA6).

Nice, in this case you just missed to upload your key [on GitHub](https://help.github.com/articles/adding-a-new-gpg-key-to-your-github-account/).
Sorry for the wrong-dated commits. Had a wrong system clock here.

**Comment by dbrgn** [comment]
> Nice, in this case you just missed to upload your key on GitHub.

Nope, it's the Threema key, not my personal one. And Github doesn't render tag signatures as far as I know.

You can verify signatures on the command line instead.

**Comment by dbrgn** [comment]
Thanks!

**Pull request merged**
